### ISSUE TITLE
I can't see  this file autogen.py

### ISSUE THREAD

**Issue by wunengguang** [koulanurag/conformal#1]
hello sir , I  run python  autogen.py  but system tell me  no such file or directory .so ,I open docs directory ,actually ，I can't see  this file autogen.py

**Comment by koulanurag** [comment]
Thanks for reaching and pointing out the issue. I have updated the docs to address the same.

Also, I am no longer actively developing this project. However, feel free to reach out for any issue in the existing project!

Thanks!
